Varriance
$$var(x) = \frac{\sum_{i=1}^{n} (x_i-\mu)^2}{n}$$

where $\mu$ is the mean of x, and we have $n$ values in our vector

Covarriance
$$ cov(x,y) = \frac{\sum_{i=1}^{n} (x_i-\mu_x)(y_i - \mu_y)}{n}$$
where $mu_x$ is the mean of x and $mu_y$ is the mean of y

Here we are showing population var and cov. For sample of a population divide by $n-1$

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [65]:
n = 5
x = np.random.randint(low = 0, high = 10, size = n)
y = np.random.randint(low = 0, high = 10, size = n)

In [76]:


nn = 2
cov = np.zeros((nn,nn))
xm = np.stack([x,y])
for i in range(nn):
    for j in range(nn):
        x1 = xm[i,:]
        x2 = xm[j,:]
        x1_mean = x1.mean()
        x2_mean = x2.mean()
        for k in range(n):
            cov[i,j]+=  (x1[k]- x1_mean)*(x2[k] - x2_mean)
        cov[i,j]/=(n-1)

In [77]:
cov

array([[7.8 , 4.95],
       [4.95, 3.8 ]])

In [73]:
x,y

(array([2, 4, 8, 2, 7]), array([1, 1, 4, 1, 5]))

In [78]:
np.var(y, ddof = 1)

3.8

In [79]:

cov2 = np.cov(xm,ddof = 1)
cov2

array([[7.8 , 4.95],
       [4.95, 3.8 ]])

In [57]:
xm

array([[2, 7, 9, 6, 4],
       [0, 2, 6, 0, 6]])

In [3]:

# m= np.arange(10, dtype=np.float64)

# f = np.arange(10) * 2

# a = np.arange(10) ** 2.

# ddof = 1

# w = f * a

# v1 = np.sum(w)

# v2 = np.sum(w * a)

# m -= np.sum(m * w, axis=None, keepdims=True) / v1

# cov = np.dot(m * w, m.T) * v1 / (v1**2 - ddof * v2)

In [4]:
cov

2.368621947484198

In [5]:
m

array([-7.57185185, -6.57185185, -5.57185185, -4.57185185, -3.57185185,
       -2.57185185, -1.57185185, -0.57185185,  0.42814815,  1.42814815])

In [6]:
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
a

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [8]:
v1

4050.0

In [9]:
v2

241650.0

In [10]:
m

array([-7.57185185, -6.57185185, -5.57185185, -4.57185185, -3.57185185,
       -2.57185185, -1.57185185, -0.57185185,  0.42814815,  1.42814815])

In [11]:
v = np.array([[0, 2], [1, 1], [2, 0]]).T

In [12]:
v

array([[0, 1, 2],
       [2, 1, 0]])

In [13]:
np.cov(v)

array([[ 1., -1.],
       [-1.,  1.]])