# Julia kernel
* Reading `Julia 1.0 Programming - Second Edition`

In [51]:
x = 10

10

In [52]:
x

10

In [53]:
x+1

11

In [54]:
x = "my string"

"my string"

In [55]:
x

"my string"

In [56]:
pi

π = 3.1415926535897...

Make a function

In [57]:
f(x) = 2x+5

f (generic function with 1 method)

Test it

In [58]:
f(3)


11

See the LLVM code that represents the actual function

In [59]:
code_llvm(f, (Int64,)) 



; Function f
; Location: In[57]:1
; Function Attrs: uwtable
define i64 @julia_f_36148(i64) #0 {
top:
; Function *; {
; Location: int.jl:54
  %1 = shl i64 %0, 1
;}
; Function +; {
; Location: int.jl:53
  %2 = add i64 %1, 5
;}
  ret i64 %2
}


See assembly code for the function

In [60]:
code_native(f, (Int64,)) 

	.text
; Function f {
; Location: In[57]:1
	pushq	%rbp
	movq	%rsp, %rbp
; Function +; {
; Location: int.jl:53
	leaq	(%rcx,%rcx), %rax
	addq	$5, %rax
;}
	popq	%rbp
	retq
	nop
;}


In [61]:
code_native(f, (Float64,))

	.text
; Function f {
; Location: In[57]:1
	pushq	%rbp
	movq	%rsp, %rbp
; Function *; {
; Location: promotion.jl:314
; Function *; {
; Location: float.jl:399
	vaddsd	%xmm0, %xmm0, %xmm0
	movabsq	$333531064, %rax        # imm = 0x13E147B8
;}}
; Function +; {
; Location: promotion.jl:313
; Function +; {
; Location: float.jl:395
	vaddsd	(%rax), %xmm0, %xmm0
;}}
	popq	%rbp
	retq
	nopl	(%rax,%rax)
;}


In [62]:
y = 66

66

In [63]:
typeof(y)

Int64

Double quotes = string

In [64]:
z = "h"

"h"

In [65]:
typeof(z)

String

single quote = char

In [66]:
a = 'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [67]:
typeof(a)

Char

Julia tries to guess the type and won't allow some operations if types are mismatched

In [68]:
# y+z

In [69]:
# this is a comment

In [70]:
#= multi line
comment with amperstan and equals
last line =#
b = 12.3

12.3

In [71]:
typeof(b)

Float64

In [72]:
print(b)

12.3

Fancy print 

In [73]:
printstyled(b,color=:red)

12.3

In [74]:
function calc_dist(x1::Float64, x2::Float64)
    print("x1 is $x1 and x2 is $x2")
    return abs(x1 - x2)

end

calc_dist (generic function with 1 method)

In [75]:
calc_dist(1.,2.)

x1 is 1.0 and x2 is 2.0

1.0

Show a bit string representation

In [76]:
bitstring(1.4e5)

"0100000100000001000101110000000000000000000000000000000000000000"

In [77]:
d = true

true

In [78]:
e = false

false

Boolean AND or OR

In [79]:
println(d && e)
print(d || e)

false
true

In [80]:
mystring = "My string"

"My string"

Get the char value at some location in a string

In [81]:
mystring[3]

' ': ASCII/Unicode U+0020 (category Zs: Separator, space)

In [82]:
# loop over a string
for c in mystring
    print("-$c")
end

-M-y- -s-t-r-i-n-g

In [83]:
start = mystring[1:3] # note: start at 1 for strings. 
println(start)

My 


In [85]:
for i in 1:100
    print("_$i")
end

_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34_35_36_37_38_39_40_41_42_43_44_45_46_47_48_49_50_51_52_53_54_55_56_57_58_59_60_61_62_63_64_65_66_67_68_69_70_71_72_73_74_75_76_77_78_79_80_81_82_83_84_85_86_87_88_89_90_91_92_93_94_95_96_97_98_99_100

In [89]:
vector = [1,2,3]
vector2 = [4,5,6]

3-element Array{Int64,1}:
 4
 5
 6

In [87]:
typeof(vector)

Array{Int64,1}

In [91]:
vector3 = vector+vector2

3-element Array{Int64,1}:
 5
 7
 9

In [92]:
arr4 = collect(1:7)

7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7

In [94]:
push!(arr4,1)

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 1

In [96]:
eltype(arr4)

Int64

In [97]:
length(arr4)

8

In [98]:
ndims(arr4)

1

In [99]:
join(arr4, ", ")

"1, 2, 3, 4, 5, 6, 7, 1"

In [100]:
arr4[3:5]

3-element Array{Int64,1}:
 3
 4
 5

In [101]:
arr5 = zeros(3,4)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [103]:
vector5 = range(0,step = 2, length=100)

0:2:198

In [105]:
for v in vector5
    print("_$v")
end

_0_2_4_6_8_10_12_14_16_18_20_22_24_26_28_30_32_34_36_38_40_42_44_46_48_50_52_54_56_58_60_62_64_66_68_70_72_74_76_78_80_82_84_86_88_90_92_94_96_98_100_102_104_106_108_110_112_114_116_118_120_122_124_126_128_130_132_134_136_138_140_142_144_146_148_150_152_154_156_158_160_162_164_166_168_170_172_174_176_178_180_182_184_186_188_190_192_194_196_198

In [107]:
fill!(arr5, 5)

3×4 Array{Float64,2}:
 5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0
 5.0  5.0  5.0  5.0

In [109]:
vector_r = rand(Float32, 5)

5-element Array{Float32,1}:
 0.97258556
 0.16783202
 0.42016268
 0.60471106
 0.15195227

In [110]:
a = [1,2,3]
b = [2,3,4]
# append

3-element Array{Int64,1}:
 2
 3
 4

Add to an vector/array

In [112]:
append!(a,b)

6-element Array{Int64,1}:
 1
 2
 3
 2
 3
 4

In [113]:
pop!(a)

4

In [114]:
push!(a,45)

6-element Array{Int64,1}:
  1
  2
  3
  2
  3
 45

In [118]:
popfirst!(a)

1

In [119]:
a

5-element Array{Int64,1}:
  2
  3
  2
  3
 45

In [120]:
pushfirst!(a,23)

6-element Array{Int64,1}:
 23
  2
  3
  2
  3
 45

In [121]:
in(23, a)

true

In [122]:
in(-1, a)

false

In [123]:
c = sort(a)

6-element Array{Int64,1}:
  2
  2
  3
  3
 23
 45

# operations
* put a dot in front of it

In [125]:
c .+ 1

6-element Array{Int64,1}:
  3
  3
  4
  4
 24
 46

In [126]:
using LinearAlgebra

In [127]:
a = [1,2,3]
b = [4,5,6]
c = LinearAlgebra.dot(a,b)
c

32

In [128]:
d = a .+ b
d

3-element Array{Int64,1}:
 5
 7
 9

# Documentation for a type
* Use `methodswith`

In [129]:
methodswith(Array)

[1] copyto!(dest::Array{T,N} where N, doffs::Integer, src::Array{T,N} where N, soffs::Integer, n::Integer) where T in Base at array.jl:269
[2] copyto!(dest::Array{T,N} where N, src::Array{T,N} where N) where T in Base at array.jl:277
[3] copyto!(dest::BitArray, doffs::Integer, src::Array, soffs::Integer, n::Integer) in Base at bitarray.jl:428
[4] copyto!(dest::BitArray, src::Array) in Base at bitarray.jl:437
[5] copyto!(S::SharedArrays.SharedArray, A::Array) in SharedArrays at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SharedArrays\src\SharedArrays.jl:577
[6] +(A::Array, Bs::Array...) in Base at arraymath.jl:44
[7] +(A::Array, B::SparseArrays.SparseMatrixCSC) in SparseArrays at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\sparsematrix.jl:1584
[8] +(A::SparseArrays.SparseMatrixCSC, B::Array) in SparseArrays at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\sparsematrix.jl:1583
[9] -(A::SparseArrays.SparseMatrixCSC, B::Array) in SparseArrays at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\sparsematrix.jl:1585
[10] -(A::Array, B::SparseArrays.SparseMatrixCSC) in SparseArrays at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\sparsematrix.jl:1586
[11] convert(T::Type{#s546} where #s546<:SharedArrays.SharedArray, a::Array) in SharedArrays at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SharedArrays\src\SharedArrays.jl:359
[12] copy(a::T) where T<:Array in Base at array.jl:299
[13] dump(io::IOContext, x::Array, n::Int64, indent) in Base at show.jl:1656
[14] fill!(dest::Array{T,N} where N, x) where T in Base at array.jl:282
[15] getindex(A::Array, i1::Int64) in Base at array.jl:731
[16] getindex(A::Array, i1::Int64, i2::Int64, I::Int64...) in Base at array.jl:732
[17] getindex(A::Array, I::UnitRange{Int64}) in Base at array.jl:736
[18] getindex(A::Array, c::Colon) in Base at array.jl:746
[19] getindex(A::Array{S,N} where N, I::AbstractRange{Int64}) where S in Base at array.jl:756
[20] getindex(A::Array, i1::Union{Integer, CartesianIndex}, I::Union{Integer, CartesianIndex}...) in Base at multidimensional.jl:412
[21] isassigned(a::Array, i::Int64...) in Base at array.jl:204
[22] iterate(A::Array) in Base at array.jl:707
[23] iterate(A::Array, i) in Base at array.jl:707
[24] length(a::Array) in Base at array.jl:199
[25] permutedims!(P::Array{T,N}, B::Union{DenseArray{T,N}, ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T,N,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray w